name: Continuous integr8ion

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  integr8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install yarn dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build
